# Generated by Django 4.2.8 on 2023-12-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_dataset_id', models.IntegerField()),
                ('data_mission_id', models.IntegerField()),
                ('data_background', models.CharField(max_length=200)),
                ('data_question', models.CharField(max_length=200)),
                ('data_answer', models.JSONField()),
                ('data_status', models.IntegerField()),
                ('data_lastest_time', models.CharField(max_length=200)),
                ('data_area', models.CharField(max_length=200)),
                ('data_keyword', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('data_reserve', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=200)),
                ('dataset_size', models.IntegerField()),
                ('dataset_data_finished_count', models.IntegerField()),
                ('dataset_source', models.CharField(max_length=200)),
                ('dataset_task_type', models.CharField(max_length=200)),
                ('dataset_upload_time', models.CharField(max_length=200)),
                ('dataset_assign_time', models.CharField(max_length=200)),
                ('dataset_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expert_id', models.IntegerField(primary_key=True, serialize=False)),
                ('expert_name', models.CharField(max_length=200)),
                ('expert_password', models.CharField(max_length=200)),
                ('expert_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manger',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mission_expert_id', models.IntegerField()),
                ('mission_dataset_id', models.IntegerField()),
                ('mission_area', models.CharField(max_length=200)),
                ('mission_size', models.IntegerField()),
                ('mission_data_finished_count', models.IntegerField()),
                ('mission_create_time', models.CharField(max_length=200)),
                ('mission_due_time', models.CharField(max_length=200)),
                ('mission_notice', models.CharField(max_length=200)),
                ('mission_original_id', models.IntegerField()),
                ('mission_transfer', models.IntegerField()),
                ('mission_highlight', models.IntegerField()),
            ],
        ),
    ]
