# Generated by Django 4.2.8 on 2023-12-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manger',
            new_name='Manager',
        ),
    ]
