# Generated by Django 4.2.8 on 2023-12-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_data_data_id_alter_dataset_dataset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_mission_id',
            field=models.IntegerField(null=True),
        ),
    ]
