# Generated by Django 4.2.8 on 2024-01-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_data_data_answer_alter_data_data_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_area',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_background',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_keyword',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='other',
            field=models.TextField(null=True),
        ),
    ]
